### PR TITLE
feat: add website using docsify

### LINKED ISSUE #7: Website
Hello Anmol:)

I think this repo is cool and more people should know it.
I was thinking of contributing by creating a pure HTML website for this repo so that people can find it on search engines.
I was think of using [docsify ](https://docsify.js.org/)and I think it will look great.

### PR DESCRIPTION
**Pull request by Bashamega**
closes #7 
 
Hello:)
The website is done :)
image
If you want i can change theme to be dark mode.

### CODE REVIEW

**Comment by Bashamega** [comment]
@Anmol-Baranwal

**Review by Anmol-Baranwal — COMMENTED** [review]
@Bashamega 
I am sorry, as I was traveling and didn't get the time to review earlier.

Could you please use [this](https://github.com/boopathikumar018/docsify-darklight-theme?tab=readme-ov-file) to add a toggle button for light/dark mode?

They also provide the [CDN](https://docsify-darklight-theme.boopathikumar.me/#/installation) and you can read the [docs](https://docsify-darklight-theme.boopathikumar.me/#/).

I think it would be great addition so that others can toggle the mode as per their preference.

**Comment by Bashamega** [comment]
> @Bashamega 
> I am sorry, as I was traveling and didn't get the time to review earlier.
> 
> Could you please use [this](https://github.com/boopathikumar018/docsify-darklight-theme?tab=readme-ov-file) to add a toggle button for light/dark mode?
> 
> They also provide the [CDN](https://docsify-darklight-theme.boopathikumar.me/#/installation) and you can read the [docs](https://docsify-darklight-theme.boopathikumar.me/#/).
> 
> I think it would be great addition so that others can toggle the mode as per their preference.

Happy vacation

Sure I am going to check it.

**Comment by Bashamega** [comment]
Done @Anmol-Baranwal

**Comment by Anmol-Baranwal** [comment]
Thank you!
I will merge this by tomorrow.

**Review by Anmol-Baranwal — APPROVED** [review]
🚀 Looks good to me. 

> Thanks for contributing, @Bashamega. It looks so much better.

**Pull request merged**
